services:
  cassandra1:
    build: .
    container_name: cassandra1
    ports:
      - "9042:9042"
    networks:
      cassandra_net:
        ipv4_address: 192.168.122.200
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_BROADCAST_ADDRESS=192.168.122.200
      - CASSANDRA_SEEDS=192.168.122.200,192.168.122.201,192.168.122.202
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    deploy:
      resources:
        limits:
          memory: 3g

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    ports:
      - "9043:9042"
    networks:
      cassandra_net:
        ipv4_address: 192.168.122.201
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_BROADCAST_ADDRESS=192.168.122.201
      - CASSANDRA_SEEDS=192.168.122.200,192.168.122.201,192.168.122.202
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    deploy:
      resources:
        limits:
          memory: 3g

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    ports:
      - "9044:9042"
    networks:
      cassandra_net:
        ipv4_address: 192.168.122.202
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_BROADCAST_ADDRESS=192.168.122.202
      - CASSANDRA_SEEDS=192.168.122.200,192.168.122.201,192.168.122.202
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=512M
    deploy:
      resources:
        limits:
          memory: 3g

networks:
  cassandra_net:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 192.168.122.0/24
          gateway: 192.168.122.1
